# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-08 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaxf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minebtns',
            name='is_used',
        ),
    ]
