# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-08 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaxf', '0002_remove_minebtns_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='minebtns',
            name='is_used',
            field=models.BooleanField(default=True, verbose_name='是否正在使用'),
        ),
    ]
